device: "cuda"
seed: 17

optimization:
  lr: 0.001

training:
  perplexity: 30
  n_epochs: 20
  early_exaggeration: 0
  early_exaggeration_constant: 5
  batch_size: 500
  bin_search_max_iter: 1000
  bin_search_tol: 0.0001
  dist_func_name: "euc"
  min_allowed_sig_sq: 0
  max_allowed_sig_sq: 1000

