device: "cpu"
seed: 50
save_model: True

problem_settings:
  reactions:
    filename: "templates_only.csv"
    fp_method: "structural"
    n_bits: 2048
    fp_type: "MorganFP"
    "include_agents": True
    "agent_weight": 1
    "non_agent_weight": 10
    "bit_ratio_agents": 0.2

optimization:
  lr: 0.002

training:
  perplexity: 30
  n_epochs: 20
  early_exaggeration: 4
  early_exaggeration_constant: 5
  batch_size: 7000
  bin_search_max_iter: 100
  bin_search_tol: 0.0001
  dist_func_name: "jaccard"
  min_allowed_sig_sq: 0
  max_allowed_sig_sq: 10000

